[general]
connection = ""
output = "CorelaiPrimeDatabase.fs"
namespace = "Corelai.Prime.Bff"
cli_mutable = true
[sqlhydra_query_integration]
provider_db_type_attributes = true
table_declarations = true
[readers]
reader_type = "Npgsql.NpgsqlDataReader"
[filters]
include = ["time/*"]
exclude = ["public/flyway_schema_history"]
