name: corelai

services:
  
  nginx:
    image: corelai-nginx-local
    ports:
      - "80:80"
    networks:
      - corelai-network

  primeapp:
    image: corelai-prime-app-local
    ports:
      - "33000:80"
    expose:
      - "80"
    networks:
      - corelai-network

  primebff:
    image: corelai-prime-bff-local
    ports:
      - "34000:80"
    expose:
      - "80"
    environment:
      ASPNETCORE_HTTP_PORTS: "80"
      Storage__CorelaiPrimeBffDbConnectionString: ${CORELAI_Storage__CorelaiPrimeBffDbConnectionString}
    networks:
      - corelai-network
      - prime-network

  primedb:
    image: postgres:17
    ports:
      - "35000:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${CORELAI_POSTGRES_DB}
      POSTGRES_USER: ${CORELAI_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CORELAI_POSTGRES_PASSWORD}
    networks:
      - prime-network


networks:
  corelai-network:
    driver: bridge
  prime-network:
    driver: bridge


#  Directive	Description
#  ports	🔓 Exposes the container port to the host machine, making it accessible via localhost or external IP.
#  expose	🔐 Makes the port available only to other containers in the same Docker network. It is not accessible from the host.
