name: corelai

services:
  
  nginx:
    image: corelai-nginx-local
    ports:
      - "80:80"
    networks:
      - corelai-network

  prime-app:
    image: corelai-prime-app-local
    ports:
      - "33000:80"
    expose:
      - "80"
    networks:
      - corelai-network

  prime-bff:
    image: corelai-prime-bff-local
    ports:
      - "34000:80"
    expose:
      - "80"
    environment:
      ASPNETCORE_HTTP_PORTS: "80"
      Storage__PrimeBffDbConnectionString: ${CORELAI_Storage__PrimeBffDbConnectionString}
    networks:
      - corelai-network
      - prime-network

  prime-bff-db:
    image: postgres:17
    ports:
      - "35000:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${CORELAI_PrimeBffDb}
      POSTGRES_USER: ${CORELAI_PrimeBffDbUser}
      POSTGRES_PASSWORD: ${CORELAI_PrimeBffDbPassword}
    networks:
      - prime-network

  prime-bff-db-flyway:
    image: corelai-prime-bff-db-flyway-local
    depends_on:
      - prime-bff-db
    command: -url=jdbc:postgresql://prime-bff-db:5432/${CORELAI_PrimeBffDb} 
             -user=${CORELAI_PrimeBffDbUser} 
             -password=${CORELAI_PrimeBffDbPassword}
             -locations=filesystem:/flyway/sql
             migrate
    networks:
      - prime-network

networks:
  corelai-network:
    driver: bridge
  prime-network:
    driver: bridge


#  Directive	Description
#  ports	🔓 Exposes the container port to the host machine, making it accessible via localhost or external IP.
#  expose	🔐 Makes the port available only to other containers in the same Docker network. It is not accessible from the host.
