name: corelai

services:
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /etc/corelai/certbot/www/:/var/www/certbot/:rw
      - /etc/corelai/certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - corelai-network
  
  nginx:
    image: corelai-nginx-uat
    ports:
      - "80:80"
      - "443:443"
    #restart: always
    volumes:
      - /etc/corelai/certbot/www/:/var/www/certbot/:ro
      - /etc/corelai/certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - corelai-network

  prime-app:
    image: corelai-prime-app-uat
    expose:
      - "80"
    networks:
      - corelai-network

  prime-bff:
    image: corelai-prime-bff-uat
    expose:
      - "80"
    environment:
      ASPNETCORE_HTTP_PORTS: "80"
      Storage__PrimeBffDbConnectionString: ${CORELAI_Storage__PrimeBffDbConnectionString}
    networks:
      - corelai-network
      - prime-network

  prime-bff-db:
    image: corelai-prime-bff-db-uat
    ports:
      - "192.168.0.12:5000:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${CORELAI_PrimeBffDb}
      POSTGRES_USER: ${CORELAI_PrimeBffDbUser}
      POSTGRES_PASSWORD: ${CORELAI_PrimeBffDbPassword}
    volumes:
      - /data/corelai/prime/bff-db:/var/lib/postgresql/data
    networks:
      - prime-network

  prime-bff-db-flyway:
    image: corelai-prime-bff-db-flyway-uat
    command:
      - -url=jdbc:postgresql://prime-bff-db:5432/${CORELAI_PrimeBffDb}
      - -user=${CORELAI_PrimeBffDbUser}
      - -password=${CORELAI_PrimeBffDbPassword}
      - -locations=filesystem:/flyway/sql
      - migrate
    networks:
      - prime-network

networks:
  corelai-network:
    driver: bridge
  prime-network:
    driver: bridge