name: corelai

services:
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /etc/corelai/certbot/www/:/var/www/certbot/:rw
      - /etc/corelai/certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - corelai-network
  
  nginx:
    image: corelai-nginx-uat
    ports:
      - "80:80"
      - "443:443"
    #restart: always
    volumes:
      - /etc/corelai/certbot/www/:/var/www/certbot/:ro
      - /etc/corelai/certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - corelai-network

  primeapp:
    image: corelai-prime-app-uat
    ports:
      - "3000:80"
    networks:
      - corelai-network




networks:
  corelai-network:
    driver: bridge