name: corelai

services:
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /etc/corelai/certbot/www/:/var/www/certbot/:rw
      - /etc/corelai/certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - corelai-network
  
  nginx:
    image: corelai-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    #restart: always
    volumes:
      - /etc/corelai/certbot/www/:/var/www/certbot/:ro
      - /etc/corelai/certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - corelai-network

  primeapp:
    image: corelai-prime-app-prod
    expose:
      - "80"
    networks:
      - corelai-network

  primebff:
    image: corelai-prime-bff-prod
    expose:
      - "80"
    environment:
      ASPNETCORE_HTTP_PORTS: "80"
    networks:
      - corelai-network


networks:
  corelai-network:
    driver: bridge